
import User from '../Models/User.js';

/**
 * @openapi
 * /users/check-email:
 *   get:
 *     tags:
 *       - /users
 *     summary: Find users by gmail
 *     description: Returns a user if it matches of any registered email
 *     parameters:
 *       - in: query
 *         name: email
 *         required: true
 *         type: string
 *         
 *     responses:
 *        '200':
 *          description: OK
 *          content:
 *            application/json:
 *              schema:
 *                $ref: '#/components/schemas/User'
 *          '400':
 *            description: Email are required
 *          '404':
 *            description: User not found
 *          '500':
 *            description: Internal Server Error
 * 
 *components:
 *  schemas:
 *   User:
 *     type: object
 *     properties:
 *       _id:
 *         type: string
 *         description: Auto-generated by MongoDB
 *       name:
 *         type: string
 *       lastname:
 *         type: string
 *       email:
 *         type: string
 *       rol:
 *         type: string
 *         enum: [teacher, student]
 *       creationDate:
 *         type: string
 *         format: date-time
 *       
 *         
 *     example:
 *        _id: 64766f0d4bc2991546b5bbb3
 *        name: "Michael"
 *        lastname": "Johnson"
 *        email: "michael.johnson@gmail.com"
 *        rol: "teacher"
 *        creationDate: 2023-05-30T21:47:57.518+00:00
 * 
 */

const getUserByEmail=async(request, response,next)=>{
  try {
    const {email}=request.query;
    const user=await User.findOne({email});
  if (!email) {
    return response.status(400).send('Email are required');
  }
  if (!user) {
    return response.status(404).send('User not found');
  } 
  return response.status(200).json(user);
  
    
  } catch (error) {
    next(error);
  }
  
}
export default getUserByEmail;